In [ ]:
import pandas as pd

In [3]:
# ORTHO-EAST

df_desc = pd.read_csv("data/alqueva_calibrated_asc_desc_2019_2023/EGMS_L2b_052_0848_IW2_VV_2019_2023_1/EGMS_L2b_052_0848_IW2_VV_2019_2023_1.csv")
df_asc = pd.read_csv("data/alqueva_calibrated_asc_desc_2019_2023/EGMS_L2b_147_0224_IW2_VV_2019_2023_1/EGMS_L2b_147_0224_IW2_VV_2019_2023_1.csv")

In [4]:
df_desc

,pid,mp_type,latitude,longitude,easting,northing,height,height_wgs84,line,pixel,...,20230904,20230916,20230928,20231010,20231022,20231103,20231115,20231127,20231209,20231221
0,4EM4h00p9W,0,38.287821,-7.313548,2810422.31,1861750.76,185.5,240.7,3,26,...,-10.4,-12.2,-10.6,-6.5,-10.7,1.6,-4.4,-7.8,-0.5,-17.6
1,4EM4h00H9R,0,38.290389,-7.329765,2809092.57,1862351.02,178.6,233.8,1,397,...,-12.7,-8.1,-8.7,-4.5,-12.2,-12.5,-10.8,-10.0,-10.1,-6.9
2,4EM4h00H9S,0,38.290388,-7.329755,2809093.37,1862350.68,175.1,230.3,1,398,...,-8.8,-4.9,-5.9,-0.8,-9.0,-11.0,-5.0,0.8,-5.5,-6.4
3,4EM4h01NLc,0,38.289922,-7.330067,2809056.21,1862306.38,182.3,237.5,5,400,...,-12.2,-14.1,-2.1,-14.7,-19.3,-9.0,-10.3,-13.7,-14.0,-9.4
4,4EM4h016Ks,0,38.290941,-7.336324,2808543.82,1862541.14,184.0,239.2,4,542,...,13.4,1.5,5.5,5.0,3.9,4.8,4.5,4.6,0.3,1.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226440,4EM4h6WqMM,0,38.205181,-8.062672,2744485.21,1868003.83,99.4,154.3,1472,16794,...,-9.0,-10.6,-11.6,-10.0,-11.0,-11.7,-8.9,-10.2,-10.4,-9.1
226441,4EM4h6WqMO,0,38.205202,-8.062822,2744472.87,1868009.15,104.5,159.4,1472,16796,...,-8.4,-9.0,-6.7,-6.1,-10.9,-12.7,-10.3,-10.9,-11.6,-11.7
226442,4EM4h6WZJz,0,38.205539,-8.064358,2744349.51,1868077.46,103.0,157.9,1471,16835,...,-4.3,-4.4,-6.1,-5.9,-1.8,0.3,-1.9,2.9,6.9,1.4
226443,4EM4h6WqN0,0,38.205420,-8.064419,2744341.53,1868065.84,108.6,163.5,1472,16834,...,-0.6,0.4,-4.5,-1.0,1.8,7.7,0.4,7.5,6.7,5.3
226444,4EM4h6WZPC,0,38.207360,-8.077686,2743253.41,1868550.66,119.8,174.7,1471,17158,...,-18.8,-19.0,-18.9,-14.8,-18.2,-19.3,-19.8,-16.2,-17.8,-11.2

In [5]:
df_asc

,pid,mp_type,latitude,longitude,easting,northing,height,height_wgs84,line,pixel,...,20230829,20230910,20230922,20231004,20231016,20231109,20231121,20231203,20231215,20231227
0,4eR7j0000B,4549,38.027594,-7.743627,2767688.47,1842235.70,174.7,229.7,0,11,...,19.9,18.2,19.1,19.4,17.7,19.4,17.9,23.0,22.1,19.7
1,4eR7j0000N,0,38.027671,-7.743092,2767736.11,1842233.08,175.2,230.2,0,23,...,-2.1,-0.4,5.1,3.3,0.2,13.1,8.3,-10.3,10.0,-9.2
2,4eR7j0000Q,0,38.027682,-7.743014,2767743.09,1842232.70,171.7,226.7,0,26,...,12.5,10.2,11.0,11.0,12.6,11.6,14.3,17.8,6.8,4.0
3,4eR7j0000a,0,38.027750,-7.742540,2767785.28,1842230.38,173.9,228.9,0,36,...,-2.4,-14.1,-2.4,-0.2,5.3,-4.2,1.8,-5.3,7.1,2.8
4,4eR7j0000d,0,38.027771,-7.742393,2767798.35,1842229.66,174.8,229.8,0,39,...,-3.8,-10.3,-7.0,-1.6,3.0,-3.4,6.2,5.6,1.1,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1186521,4eR7j6TIhB,0,38.348657,-6.767709,2858485.49,1857681.54,534.5,590.0,1459,24373,...,-6.6,-6.6,-5.1,-6.0,-5.4,-1.3,-6.6,-5.2,-5.5,-3.6
1186522,4eR7j6TIhC,0,38.348656,-6.767715,2858484.88,1857681.57,530.9,586.3,1459,24374,...,-5.6,-5.8,-7.2,-4.0,-2.8,-8.6,-7.5,-7.0,-6.2,-2.4
1186523,4eR7j6T1eZ,0,38.348671,-6.766654,2858576.08,1857662.77,534.7,590.1,1458,24399,...,-5.2,-7.1,-11.6,-7.9,-8.7,6.9,3.0,-11.4,12.4,-11.3
1186524,4eR7j6TIha,0,38.348783,-6.766771,2858568.53,1857677.12,530.8,586.2,1459,24398,...,-11.6,-8.9,-13.7,-10.4,-9.7,-4.4,-0.7,-9.0,-10.1,-3.1
1186525,4eR7j6TIhb,0,38.348789,-6.766726,2858572.49,1857676.90,531.2,586.6,1459,24399,...,-4.0,-7.9,-12.6,-10.0,-9.4,-13.5,0.1,-10.5,-13.7,-8.0

In [6]:
# Definir os limites Alqueva
norte_min = 1855050
norte_max = 1855850
este_min = 2792250
este_max = 2793250

# Aplicar o filtro
df_desc = df_desc[
    (df_desc['northing'] >= norte_min) & (df_desc['northing'] <= norte_max) &
    (df_desc['easting'] >= este_min) & (df_desc['easting'] <= este_max)
]

df_desc

,pid,mp_type,latitude,longitude,easting,northing,height,height_wgs84,line,pixel,...,20230904,20230916,20230928,20231010,20231022,20231103,20231115,20231127,20231209,20231221
129276,4EM4h3zlyc,0,38.198409,-7.490936,2793227.41,1855609.57,152.2,207.3,901,3506,...,-2.0,8.7,4.3,4.7,-6.3,-0.7,2.6,-1.7,-1.8,-6.8
129277,4EM4h40sB8,0,38.198063,-7.492095,2793120.35,1855595.34,152.6,207.8,905,3530,...,-8.4,3.3,-1.0,-0.1,0.6,-6.3,-16.4,5.7,-3.4,-6.5
129278,4EM4h40sB9,0,38.198071,-7.492150,2793115.82,1855597.28,153.4,208.6,905,3531,...,-7.5,-8.0,-1.9,-2.8,-0.3,-6.0,-2.4,-6.3,-10.0,-13.1
129279,4EM4h40sBK,0,38.198140,-7.492641,2793075.38,1855614.65,154.4,209.5,905,3542,...,-12.1,-11.8,-17.2,-6.6,-15.5,-6.9,-11.4,-11.2,-24.9,-2.9
129280,4EM4h40sBN,0,38.198159,-7.492773,2793064.49,1855619.33,154.5,209.7,905,3545,...,-12.1,-7.7,-10.8,-6.3,-5.9,-9.0,-8.1,-7.3,-14.0,-7.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144120,4EM4h4FAlN,0,38.192575,-7.500200,2792302.25,1855163.93,135.5,190.7,957,3689,...,-1.4,-5.1,-4.1,-7.7,-4.6,-4.3,-6.6,-7.2,-10.3,1.5
144121,4EM4h4FRnx,5896,38.192272,-7.498961,2792401.47,1855106.26,131.7,186.8,958,3661,...,-11.9,-12.5,-13.0,-11.1,-11.9,-15.3,-13.9,-16.9,-16.8,-16.5
144122,4EM4h4FRo2,7461,38.192307,-7.499206,2792381.29,1855114.92,133.6,188.8,958,3666,...,-4.9,-6.3,-6.5,-4.6,-7.3,-11.7,-11.5,-12.4,-14.9,-11.6
144125,4EM4h4FAla,0,38.192655,-7.500768,2792255.44,1855184.04,135.9,191.1,957,3702,...,-9.8,-12.0,-4.8,-3.0,-10.3,-4.8,-14.3,5.2,-16.2,-14.6
145564,4EM4h4GGwu,4278,38.191861,-7.498765,2792408.99,1855057.85,138.9,194.1,961,3652,...,-15.3,-15.4,-14.2,-15.9,-16.1,-16.6,-14.9,-14.4,-14.1,-14.5

In [7]:
# Definir os limites Alqueva
norte_min = 1855050
norte_max = 1855850
este_min = 2792250
este_max = 2793250

# Aplicar o filtro
df_asc = df_asc[
    (df_asc['northing'] >= norte_min) & (df_asc['northing'] <= norte_max) &
    (df_asc['easting'] >= este_min) & (df_asc['easting'] <= este_max)
]

df_asc

,pid,mp_type,latitude,longitude,easting,northing,height,height_wgs84,line,pixel,...,20230829,20230910,20230922,20231004,20231016,20231109,20231121,20231203,20231215,20231227
821977,4eR7j4UrEJ,5072,38.191540,-7.500285,2792271.61,1855053.61,160.7,215.9,1014,6299,...,18.3,14.1,11.6,14.4,9.8,11.6,15.3,14.7,13.8,10.4
821979,4eR7j4VPKX,5438,38.191826,-7.500066,2792296.77,1855080.18,150.2,205.4,1016,6309,...,3.4,3.6,3.5,2.0,2.5,7.4,6.2,8.9,8.1,7.1
821980,4eR7j4VPKg,7007,38.191869,-7.499765,2792323.55,1855078.72,144.5,199.7,1016,6318,...,-6.5,7.3,6.5,2.9,-0.5,-17.4,-19.7,5.4,-12.2,-13.3
821981,4eR7j4VgNi,7164,38.191990,-7.499813,2792322.13,1855092.77,143.1,198.3,1017,6318,...,-9.9,-1.6,2.5,4.0,-7.0,-19.7,-20.1,-0.3,-9.1,-14.5
821983,4eR7j4VPLW,6379,38.192143,-7.497819,2792496.35,1855069.28,125.7,180.9,1016,6370,...,-19.4,-15.7,-18.1,-22.6,-23.1,-21.0,-28.5,-30.3,-20.6,-23.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
866039,4eR7j4ibg9,0,38.197814,-7.501022,2792350.48,1855747.63,166.1,221.3,1064,6313,...,4.2,4.3,8.2,9.6,8.6,16.6,8.3,13.3,16.8,-2.1
866040,4eR7j4isj5,0,38.197909,-7.501258,2792332.40,1855762.58,169.4,224.6,1065,6307,...,0.8,12.4,14.7,-1.4,5.9,10.9,5.8,10.7,12.5,13.4
866041,4eR7j4isj6,0,38.197911,-7.501242,2792333.82,1855762.51,167.6,222.8,1065,6308,...,2.2,12.3,15.1,3.3,7.4,10.0,5.0,10.6,10.5,12.6
866042,4eR7j4j9m7,0,38.198029,-7.501305,2792331.09,1855776.62,168.1,223.3,1066,6307,...,0.8,12.7,16.5,-5.2,9.2,8.6,9.9,13.0,11.9,12.9
870410,4eR7j4kX1I,0,38.198617,-7.501665,2792313.59,1855847.45,150.0,205.2,1071,6308,...,1.5,-10.7,-5.3,-2.9,-2.5,-4.0,-4.6,-8.1,-9.4,-6.8